### ISSUE TITLE
Can't compile (OS X)

### ISSUE THREAD

**Issue by jwosty** [gstreamer-sharp/gstreamer-sharp#3]
I've been able to successfully compile and install GTK#, but GST# won't build, failing with:

    Making all in sources
    /usr/bin/gmcs -nowarn:169 -unsafe -target:library -r:/Library/Frameworks/Mono.Framework/Versions/3.12.0/lib/pkgconfig/../../lib/mono/gtk-sharp-3.0/glib-sharp.dll  \
		AssemblyInfo.cs custom/*.cs  generated/*.cs -out:../out/gstreamer-sharp.dll
    AssemblyInfo.cs(25,12): warning CS1699: Use compiler option `keyfile' or appropriate project settings instead of `AssemblyKeyFile' attribute
    custom/Caps.cs(31,10): error CS0246: The type or namespace name `Structure' could not be found. Are you missing an assembly reference?
    custom/FFTF32.cs(33,139): error CS0246: The type or namespace name `FFTF32Complex' could not be found. Are you missing an assembly reference?
    custom/FFTF32.cs(35,41): error CS0234: The type or namespace name `FFTF32Complex' does not exist in the namespace `Gst.FFT'. Are you missing an assembly reference?
    custom/FFTF32.cs(42,44): error CS0234: The type or namespace name `FFTWindow' does not exist in the namespace `Gst.FFT'. Are you missing an assembly reference?
    custom/Iterator.cs(40,10): error CS0234: The type or namespace name `IteratorResult' does not exist in the namespace `Gst'. Are you missing an assembly reference?
    custom/NavigationQuery.cs(23,37): error CS0234: The type or namespace name `Query' does not exist in the namespace `Gst'. Are you missing an assembly reference?
    custom/NavigationQuery.cs(23,58): error CS0246: The type or namespace name `NavigationCommand' could not be found. Are you missing an assembly reference?
    custom/TagList.cs(55,20): error CS0234: The type or namespace name `TagMergeMode' does not exist in the namespace `Gst'. Are you missing an assembly reference?
    custom/Value.cs(456,10): error CS0104: `DateTime' is an ambiguous reference between `System.DateTime' and `GLib.DateTime'
    /Library/Frameworks/Mono.framework/Versions/3.12.0/lib/mono/2.0/mscorlib.dll (Location of the symbol related to previous error)
    /Library/Frameworks/Mono.Framework/Versions/3.12.0/lib/pkgconfig/../../lib/mono/gtk-sharp-3.0/glib-sharp.dll (Location of the symbol related to previous error)
    custom/Value.cs(476,16): error CS0104: `DateTime' is an ambiguous reference between `System.DateTime' and `GLib.DateTime'
    /Library/Frameworks/Mono.framework/Versions/3.12.0/lib/mono/2.0/mscorlib.dll (Location of the symbol related to previous error)
    /Library/Frameworks/Mono.Framework/Versions/3.12.0/lib/pkgconfig/../../lib/mono/gtk-sharp-3.0/glib-sharp.dll (Location of the symbol related to previous error)
    Compilation failed: 10 error(s), 1 warnings
    make[1]: *** [../out/gstreamer-sharp.dll] Error 1
    make: *** [all-recursive] Error 1

I've tried both `master` and the latest release, but both give me the same problem.

**Comment by stsundermann** [comment]
Are you trying to build master or 0.99.0? I recommend building against master if you can depend on gtk# master, because master is much more stable than 0.99.0

**Comment by jwosty** [comment]
Alright, just installed GTK# master and it seems to have solved that issue. However, now I'm getting this:

    Making all in sources
    cp ./gstreamer-sharp-api.raw gstreamer-sharp-api.xml
    chmod u+w gstreamer-sharp-api.xml
    api=./gstreamer-sharp-api.xml --metadata=./gstreamer-sharp.metadata
    /bin/sh: --metadata=./gstreamer-sharp.metadata: No such file or directory
    make[1]: [gstreamer-sharp-api.xml] Error 127 (ignored)
    rm -rf generated/* && \
    	 --generate ./gstreamer-sharp-api.xml -I:/Library/Frameworks/Mono.Framework/Versions/3.12.0/lib/pkgconfig/../../share/gapi-3.0/glib-api.xml  -I:/Library/Frameworks/Mono.Framework/Versions/3.12.0/lib/pkgconfig/../../share/gapi-3.0/gio-api.xml -I:/Library/Frameworks/Mono.Framework/Versions/3.12.0/lib/pkgconfig/../../share/gapi-3.0/glib-api.xml  \
    		--outdir=generated \
    		--glue-filename=glue/generated.c --gluelib-name=libgstreamersharpglue-1.0.0.dll \
    		--glue-includes=gst/gst.h,gst/gst.h,gst/app/app.h,gst/audio/audio.h,gst/base/base.h,gst/controller/controller.h,gst/fft/fft.h,gst/net/net.h\,gst/pbutils/pbutils.h,gst/rtp/rtp.h,gst/rtsp/rtsp.h,gst/sdp/sdp.h,gst/tag/tag.h,gst/video/video.h \
	 	--assembly-name=gstreamer-sharp && touch generated-stamp
    /bin/sh: --generate: command not found
    make[1]: *** [generated-stamp] Error 127
    make: *** [all-recursive] Error 1

Any idea why this is happening? So many issues on my computer...

**Comment by stsundermann** [comment]
No idea what's causing this. It seems like the gapi tool is not found. Are you running *GST#* master? Did you reconfigure after reinstalling *GTK#* master?

**Comment by jwosty** [comment]
Yes, and yes. And to make sure, I started fresh and re cloned the repo.

**Comment by stsundermann** [comment]
What does ```which gapi3-codegen``` yield?

**Comment by jwosty** [comment]
Doesn't exist for me.

**Comment by stsundermann** [comment]
That's weird, it should have been installed with gtk-sharp. What's the output of pkg-config gapi-3.0 --variable=prefix give?

**Comment by jwosty** [comment]
Hmm, that gives the expected location: `/Library/Frameworks/Mono.Framework/Versions/3.12.0/lib/pkgconfig/../..`

**Comment by jwosty** [comment]
Ah, I forgot that GTK# gave this error far along in the make process:

    [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: Path is invalid
    Parameter name: path
      at System.IO.Directory.ValidateDirectoryListing (System.String path, System.String searchPattern, System.Boolean& stop) [0x00000] in <filename unknown>:0 
      at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, FileAttributes mask, FileAttributes attrs) [0x00000] in <filename unknown>:0 
      at System.IO.Directory.GetFiles (System.String path, System.String searchPattern) [0x00000] in <filename unknown>:0 
      at Mono.CSharp.CommandLineParser.ProcessSourceFiles (System.String spec, Boolean recurse, System.Collections.Generic.List`1 sourceFiles) [0x00000] in <filename unknown>:0 
      at Mono.CSharp.CommandLineParser.ParseArguments (Mono.CSharp.CompilerSettings settings, System.String[] args) [0x00000] in <filename unknown>:0 
      at Mono.CSharp.CommandLineParser.ParseArguments (System.String[] args) [0x00000] in <filename unknown>:0 
      at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0 
    make[3]: *** [valtest.exe] Error 1

Looks like this is actually an issue with GTK# -- I mistakenly assumed that was irrelevant since there didn't appear to be anything important left.

**Comment by stsundermann** [comment]
Alright, the problem is that which gapi3-codegen is used to determine the gapi location but it's not in your path. You can temporarily add the folder to your path.
We should use pkg-config to look for the gapi toolchain

**Comment by stsundermann** [comment]
The gtk# build failure is fixed in https://github.com/mono/gtk-sharp/pull/130 but it hasn't been merged yet. You can cherry pick that commit.

**Comment by jwosty** [comment]
Trying this out; I'll check back if I have any other problems.

**Comment by jwosty** [comment]
Alright, your commit fixed GTK# successfully for me, but I'm still getting the same error. I have to go for now though, I'll be back on this later.

**Comment by jwosty** [comment]
Was able to get it to build, but after some playing around with it, it now crashes when trying to load libgstreamersharpglue-1.0.0**.so**. It's obviously not finding any `.so` libraries (as `gstreamer-sharp.dll.config` specifically says to look for) on this OS X machine, and the only related files I can find are:

    /Library/Frameworks/Mono.framework/Versions/3.12.1/lib/libgstreamersharpglue-1.0.0.a
    /Library/Frameworks/Mono.framework/Versions/3.12.1/lib/libgstreamersharpglue-1.0.0.la

**Comment by stsundermann** [comment]
That's weird. I never tested installing to anything else than /usr or /usr. Can you check if the glue library was installed somewhere in those folders? You can also copy the .so manually from sources/glue/.libs/

**Comment by jwosty** [comment]
There is no .so library in there, just some object files, their archives, and libtool stuff:

    $ cd sources/glue && find .
    .
    ./.deps
    ./.deps/libgstreamersharpglue_1_0_0_la-generated.Plo
    ./.deps/libgstreamersharpglue_1_0_0_la-gobject.Plo
    ./.libs
    ./.libs/libgstreamersharpglue-1.0.0.a
    ./.libs/libgstreamersharpglue-1.0.0.la
    ./.libs/libgstreamersharpglue-1.0.0.lai
    ./generated.c
    ./gobject.c
    ./libgstreamersharpglue-1.0.0.la
    ./libgstreamersharpglue_1_0_0_la-generated.lo
    ./libgstreamersharpglue_1_0_0_la-generated.o
    ./libgstreamersharpglue_1_0_0_la-gobject.lo
    ./libgstreamersharpglue_1_0_0_la-gobject.o
    ./Makefile
    ./Makefile.am
    ./Makefile.in

No errors upon recompiling, either...

**Comment by BoBeR182** [comment]
git clone git://git.gnome.org/banshee
cd banshee
git clone git://github.com/mono/gtk-sharp.git
cd gtk-sharp
./autogen.sh
make
sudo make install 
cd ..
git clone git@github.com:gstreamer-sharp/gstreamer-sharp
cd gstreamer-sharp
git checkout 1.0
./autogen.sh --prefix=/usr
make
sudo make install 
cd ..
git clone git://github.com/mono/taglib-sharp.git
cd taglib-sharp
./autogen.sh 
make
sudo make install
cd ..

./authgen.sh
make

~/banshee$ make 
Making all in build
Making all in pkg-config
Making all in m4
Making all in data
Making all in audio-profiles
Making all in desktop-files
Found cached translation database
Merging translations into banshee-audiocd.desktop.
Making all in icon-theme-hicolor
Making all in help
Making all in src
Making all in Hyena
Making all in build
Making all in m4
Making all in pkg-config
Making all in Hyena
Making all in Hyena.Data.Sqlite
Making all in Hyena.Gui
Making all in Libraries
Making all in Migo
Making all in Mono.Media
Making all in Mtp
Making all in MusicBrainz
Making all in Lastfm
Making all in Lastfm.Gui
Making all in Core
Making all in Banshee.CollectionIndexer
Making all in Banshee.Core
Making all in Banshee.Services
Making all in Banshee.Widgets
Making all in Banshee.ThickClient
Making all in Banshee.WebBrowser
Making all in libossifer
Making all in Dap
Making all in Banshee.Dap
Making all in Banshee.Dap.AppleDevice
Making all in Banshee.Dap.MassStorage
Making all in Banshee.Dap.Mtp
Making all in Banshee.Dap.Karma
Making all in Extensions
Making all in Banshee.AmazonMp3
Making all in Banshee.AmazonMp3.Store
Making all in Banshee.Audiobook
Making all in Banshee.BooScript
Making all in Banshee.Bpm
Making all in Banshee.CoverArt
Making all in Banshee.Daap
Making all in Banshee.Emusic
Making all in Banshee.Emusic.Store
Making all in Banshee.FileSystemQueue
Making all in Banshee.InternetArchive
Making all in Banshee.Fixup
Making all in Banshee.InternetRadio
Making all in Banshee.Lastfm
Making all in Banshee.LastfmStreaming
Making all in Banshee.LibraryWatcher
Making all in Banshee.MiniMode
Making all in Banshee.Mpris
Making all in Banshee.MiroGuide
Making all in Banshee.MultimediaKeys
Making all in Banshee.NotificationArea
Making all in Banshee.NowPlaying
Making all in Banshee.OpticalDisc
Making all in Banshee.PlayerMigration
Making all in Banshee.PlayQueue
Making all in Banshee.MediaPanel
Making all in Banshee.Podcasting
Making all in Banshee.Sample
Making all in Banshee.SoundMenu
Making all in Banshee.SqlDebugConsole
Making all in Banshee.Torrent
Making all in Banshee.RemoteAudio
Making all in Banshee.UbuntuOneMusicStore
Making all in Banshee.UPnPClient
Making all in Banshee.Wikipedia
Making all in Banshee.YouTube
Making all in Backends
Making all in Banshee.Gio
Making all in Banshee.Gnome
Making all in Banshee.GStreamer
Making all in libbanshee
Making all in Banshee.GStreamerSharp
  MCS   ../../../bin/Banshee.GStreamerSharp.dll
./Banshee.GStreamerSharp/VideoManager.cs(124,58): error CS0266: Cannot implicitly convert type `System.IntPtr' to `ulong'. An explicit conversion exists (are you missing a cast?)
./Banshee.GStreamerSharp/VideoManager.cs(152,54): error CS0266: Cannot implicitly convert type `System.IntPtr' to `ulong'. An explicit conversion exists (are you missing a cast?)
Compilation failed: 2 error(s), 0 warnings
make[4]: *** [../../../bin/Banshee.GStreamerSharp.dll] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
